### ISSUE TITLE
Bug about seeding

### ISSUE THREAD

**Issue by kakolats** [mnfst/manifest#25]
Whenever i follow all the instructions in  the documentation and arrive to the stage where i must execute npm run seed, i have this error 

test-app\server\node_modules\typeorm\src\driver\mysql\MysqlQueryRunner.ts:222
                                new QueryFailedError(query, parameters, err),
                                ^
QueryFailedError: ER_NO_SUCH_TABLE: Table 'case.notifications' doesn't exist
    at Query.<anonymous> (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\typeorm\src\driver\mysql\MysqlQueryRunner.ts:222:33)    
    at Query.<anonymous> (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)        
    at Query.ErrorPacket (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\sequences\Query.js:92:8)
    at Protocol._parsePacket (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\Connection.js:88:28) {
  query: 'DELETE FROM notifications',
  parameters: undefined,
  driverError: Error: ER_NO_SUCH_TABLE: Table 'case.notifications' doesn't exist
      at Query.Sequence._packetToError (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\Connection.js:526:10)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      --------------------
      at Protocol._enqueue (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\mysql\lib\Connection.js:198:25)
      at C:\Users\LENOVO\Documents\Angular\Multivers\Test\Case\test-app\server\node_modules\typeorm\src\driver\mysql\MysqlQueryRunner.ts:194:36
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlMessage: "Table 'case.notifications' doesn't exist",
    sqlState: '42S02',
    index: 0,
    sql: 'DELETE FROM notifications'
  },
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: "Table 'case.notifications' doesn't exist",
  sqlState: '42S02',
  index: 0,
  sql: 'DELETE FROM notifications'
}

**Comment by SebConejo** [comment]
Hello @kakolats. We close this issue because we just launched a new version of CASE. This version works differently from the V1. Please if you find a bug, create a new issue. 

Thank you
